{"description":"{{throw}} statement should have adequate successors in CFG, and therefore check enclosing try to determine jump target.\r\n\r\nIn the following code, the {{throw}} statement should have the {{catch}} block as successor, which is not the case.\r\n\r\n{code}\r\npublic class A {\r\n  void foo() {\r\n    int attemptNumber \u003d 0;\r\n    while (true) {\r\n      try {\r\n        attemptNumber++; // FP S1854 (dead store)\r\n        throw new MyException(); // should have catch block as successor\r\n      } catch (MyException e) {\r\n        if (attemptNumber \u003e\u003d 10) {\r\n          System.exit(1);\r\n        }\r\n      }\r\n    }\r\n  }\r\n\r\n  static class MyException extends Exception {  }\r\n}\r\n{code}\r\n\r\nIn the picture below, node B2 from CFG (corresponding to catch block) has no successor.\r\n !wrong-cfg.png|thumbnail!\r\n\r\n","component":"SonarJava","component_version":"5.1.1"}