{"description":"In the following code, the CFG in badly built (but was correct prior to fix of SONARJAVA-2515). \r\nWhen the break is called, from within the {{try}} block, we correctly reach the {{finally}} block, but from there we should also reach the last {{throw}} statement.\r\n\r\nThis is currently not the case.\r\n\r\n{code}\r\nabstract class A {\r\n\r\n  public void testCodeWithForLoop() {\r\n    RuntimeException e \u003d null;\r\n\r\n    for (int i \u003d 0; i \u003c 2;) {\r\n      try {\r\n        e \u003d new RuntimeException(); // FP S1854 (dead store)\r\n        break;\r\n      } finally {\r\n        doSomething();\r\n      }\r\n    }\r\n\r\n    throw e;\r\n  }\r\n\r\n  abstract void doSomething();\r\n}\r\n{code}\r\n\r\nPrior to the previous fix, we got the followling CFG (B1 being the throw statement):\r\n!java-5.0.0.12796.png|thumbnail!\r\n\r\nAfter the fix, we got the following CFG (B1 is not reached anymore from the {{finally}} block):\r\n!java-5.2.0.13398.png|thumbnail!\r\n ","component":"SonarJava","component_version":"5.3"}